/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ASUS TUF GAMING
 */
public class ViewMenuProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuProfesor
     */
    public ViewMenuProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnPersona = new javax.swing.JButton();
        btnJuegos = new javax.swing.JButton();
        btnCuestionario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jDeskEscritorio = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPersona.setBackground(new java.awt.Color(8, 189, 255));
        BtnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users-free-icon-font.png"))); // NOI18N
        BtnPersona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(BtnPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 100));

        btnJuegos.setBackground(new java.awt.Color(8, 189, 255));
        btnJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamepad-free-icon-font.png"))); // NOI18N
        btnJuegos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 110, 100));

        btnCuestionario.setBackground(new java.awt.Color(8, 189, 255));
        btnCuestionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books-free-icon-font.png"))); // NOI18N
        btnCuestionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 110, 100));

        btnSalir.setBackground(new java.awt.Color(8, 189, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit-free-icon-font.png"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 110, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 700));

        jDeskEscritorio.setBackground(new java.awt.Color(255, 255, 255));
        jDeskEscritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NutriaTitulo.png"))); // NOI18N
        jDeskEscritorio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        getContentPane().add(jDeskEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 960, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPersona;
    private javax.swing.JButton btnCuestionario;
    private javax.swing.JButton btnJuegos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane jDeskEscritorio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
