/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Shalva
 */
public class viewlogin extends javax.swing.JFrame {

    /**
     * Creates new form viewlogin
     */
    public viewlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtusername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnsalir = new javax.swing.JButton();
        btninicio1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btninicio3 = new javax.swing.JButton();
        btninicio5 = new javax.swing.JButton();
        btninicio4 = new javax.swing.JButton();
        btnInvitado = new javax.swing.JButton();
        btninicio2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("LOGIN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 180, 10));

        txtusername.setBackground(new java.awt.Color(255, 255, 255));
        txtusername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(0, 0, 0));
        txtusername.setBorder(null);
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 30));

        btnsalir.setBackground(new java.awt.Color(255, 153, 153));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-small-free-icon-font.png"))); // NOI18N
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 40, 30));

        btninicio1.setBackground(new java.awt.Color(255, 153, 153));
        btninicio1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btninicio1.setForeground(new java.awt.Color(255, 255, 255));
        btninicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sign-in-alt-free-icon-font.png"))); // NOI18N
        btninicio1.setText("Inicio");
        btninicio1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btninicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-free-icon-font.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 40, 40));

        jDialog2.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 500));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btninicio3.setBackground(new java.awt.Color(255, 153, 153));
        btninicio3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btninicio3.setForeground(new java.awt.Color(255, 255, 255));
        btninicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users-free-icon-font.png"))); // NOI18N
        btninicio3.setText("Administrador");
        btninicio3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btninicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 330, 180));

        btninicio5.setBackground(new java.awt.Color(255, 153, 153));
        btninicio5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btninicio5.setForeground(new java.awt.Color(255, 255, 255));
        btninicio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/child-head-free-icon-font.png"))); // NOI18N
        btninicio5.setText("Estudiante");
        btninicio5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btninicio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 330, 180));

        btninicio4.setBackground(new java.awt.Color(255, 153, 153));
        btninicio4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btninicio4.setForeground(new java.awt.Color(255, 255, 255));
        btninicio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-free-icon-font.png"))); // NOI18N
        btninicio4.setText("Profesor");
        btninicio4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btninicio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 330, 180));

        btnInvitado.setBackground(new java.awt.Color(255, 153, 153));
        btnInvitado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInvitado.setForeground(new java.awt.Color(255, 255, 255));
        btnInvitado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sign-in-alt-free-icon-font.png"))); // NOI18N
        btnInvitado.setText("Invitado");
        btnInvitado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnInvitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 110, 30));

        btninicio2.setBackground(new java.awt.Color(255, 153, 153));
        btninicio2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btninicio2.setForeground(new java.awt.Color(255, 255, 255));
        btninicio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-small-free-icon-font.png"))); // NOI18N
        btninicio2.setText("Salir");
        btninicio2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btninicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btninicio1;
    private javax.swing.JButton btninicio2;
    private javax.swing.JButton btninicio3;
    private javax.swing.JButton btninicio4;
    private javax.swing.JButton btninicio5;
    private javax.swing.JButton btnsalir;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
