/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Subvista;

/**
 *
 * @author Shalva
 */
public class viewJuegos extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewJuegos
     */
    public viewJuegos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarJueg = new javax.swing.JButton();
        btnCrearJuego1 = new javax.swing.JButton();
        btnScore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarJueg.setBackground(new java.awt.Color(255, 153, 153));
        btnEditarJueg.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEditarJueg.setForeground(new java.awt.Color(102, 0, 0));
        btnEditarJueg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamepad-free-icon-font.png"))); // NOI18N
        btnEditarJueg.setText("🖊");
        getContentPane().add(btnEditarJueg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 140, 120));

        btnCrearJuego1.setBackground(new java.awt.Color(255, 153, 153));
        btnCrearJuego1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCrearJuego1.setForeground(new java.awt.Color(102, 0, 0));
        btnCrearJuego1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamepad-free-icon-font.png"))); // NOI18N
        btnCrearJuego1.setText("+");
        getContentPane().add(btnCrearJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 120));

        btnScore.setBackground(new java.awt.Color(255, 153, 153));
        btnScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trophy-free-icon-font.png"))); // NOI18N
        getContentPane().add(btnScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 140, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondochido.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1080, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearJuego1;
    private javax.swing.JButton btnEditarJueg;
    private javax.swing.JButton btnScore;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
