/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Subvista;

/**
 *
 * @author Shalva
 */
public class viewCuestionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewCuestionarios
     */
    public viewCuestionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCuestionario = new javax.swing.JButton();
        btnEditarCuestionario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCuestionario.setBackground(new java.awt.Color(255, 153, 153));
        btnCrearCuestionario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCrearCuestionario.setForeground(new java.awt.Color(102, 0, 0));
        btnCrearCuestionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books-free-icon-font.png"))); // NOI18N
        btnCrearCuestionario.setText("+");
        getContentPane().add(btnCrearCuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 140, 120));

        btnEditarCuestionario.setBackground(new java.awt.Color(255, 153, 153));
        btnEditarCuestionario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEditarCuestionario.setForeground(new java.awt.Color(102, 0, 0));
        btnEditarCuestionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books-free-icon-font.png"))); // NOI18N
        btnEditarCuestionario.setText("🖊");
        getContentPane().add(btnEditarCuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 140, 120));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 20, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondochido.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1080, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuestionario;
    private javax.swing.JButton btnEditarCuestionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
